"""Add data_confidence

Revision ID: 9bc13418fd30
Revises: 89bc8e3ff9d7
Create Date: 2026-06-09 10:36:13.711530+00:00

"""
from alembic import op
import sqlalchemy as sa



revision = '9bc13418fd30'
down_revision = '89bc8e3ff9d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('data_confidence', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'data_confidence')
    # ### end Alembic commands ###
