"""Add User model

Revision ID: cca33144f5c0
Revises: 1dfaed3c4645
Create Date: 2026-06-11 17:57:28.998798+00:00

"""
from alembic import op
import sqlalchemy as sa
import os
import uuid
import bcrypt
from typing import Union, Sequence


revision: str = 'cca33144f5c0'
down_revision: Union[str, None] = '1dfaed3c4645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    admin_user = os.getenv("ADMIN_USERNAME")
    admin_pass = os.getenv("ADMIN_PASSWORD")
    if admin_user and admin_pass:
        hashed = bcrypt.hashpw(admin_pass.encode(), bcrypt.gensalt()).decode()
        op.execute(
            f"INSERT INTO users (id, username, hashed_password, role, is_active) "
            f"VALUES ('{str(uuid.uuid4())}', '{admin_user}', '{hashed}', 'ADMIN', true)"
        )
    
    analyst_user = os.getenv("ANALYST_USERNAME", "analyst")
    analyst_pass = os.getenv("ANALYST_PASSWORD")
    if analyst_user and analyst_pass:
        hashed = bcrypt.hashpw(analyst_pass.encode(), bcrypt.gensalt()).decode()
        op.execute(
            f"INSERT INTO users (id, username, hashed_password, role, is_active) "
            f"VALUES ('{str(uuid.uuid4())}', '{analyst_user}', '{hashed}', 'ANALYST', true)"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
