"""add content_hash

Revision ID: 112038031a58
Revises: add_content_status
Create Date: 2026-06-11 13:58:04.510050+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '112038031a58'
down_revision = 'add_content_status'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('tactics', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('analysis_results', sa.Column('techniques', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('content_items', sa.Column('content_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_items', 'content_hash')
    op.drop_column('analysis_results', 'techniques')
    op.drop_column('analysis_results', 'tactics')
    # ### end Alembic commands ###
