"""initial_schema

Revision ID: 1898232c9028
Revises: 
Create Date: 2026-06-07 13:49:08.877177+00:00

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '1898232c9028'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('reddit', 'telegram', 'x', 'manual', name='source_type', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'not_implemented', name='collection_run_status', native_enum=False, length=32), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('items_fetched', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_runs_source'), 'collection_runs', ['source'], unique=False)
    op.create_index('ix_collection_runs_source_started', 'collection_runs', ['source', 'started_at'], unique=False)
    op.create_index(op.f('ix_collection_runs_started_at'), 'collection_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_collection_runs_status'), 'collection_runs', ['status'], unique=False)
    op.create_index('ix_collection_runs_status_started', 'collection_runs', ['status', 'started_at'], unique=False)
    op.create_table('content_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('reddit', 'telegram', 'x', 'manual', name='source_type', native_enum=False, length=32), nullable=False),
    sa.Column('source_id', sa.String(length=512), nullable=False),
    sa.Column('author_handle', sa.String(length=512), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('media_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_content_items_source_source_id')
    )
    op.create_index(op.f('ix_content_items_collected_at'), 'content_items', ['collected_at'], unique=False)
    op.create_index(op.f('ix_content_items_source'), 'content_items', ['source'], unique=False)
    op.create_index('ix_content_items_source_collected_at', 'content_items', ['source', 'collected_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('threshold_hit', sa.Float(), nullable=False),
    sa.Column('notified_via', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('analyst_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_content_id'), 'alerts', ['content_id'], unique=False)
    op.create_index('ix_alerts_content_resolved', 'alerts', ['content_id', 'resolved'], unique=False)
    op.create_index('ix_alerts_created_resolved', 'alerts', ['created_at', 'resolved'], unique=False)
    op.create_index(op.f('ix_alerts_resolved'), 'alerts', ['resolved'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_label', sa.Enum('low', 'medium', 'high', 'critical', name='risk_label', native_enum=False, length=32), nullable=False),
    sa.Column('nlp_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vision_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_analyzed_at'), 'analysis_results', ['analyzed_at'], unique=False)
    op.create_index('ix_analysis_results_content_analyzed_at', 'analysis_results', ['content_id', 'analyzed_at'], unique=False)
    op.create_index(op.f('ix_analysis_results_content_id'), 'analysis_results', ['content_id'], unique=False)
    op.create_index('ix_analysis_results_label_score', 'analysis_results', ['risk_label', 'risk_score'], unique=False)
    op.create_index(op.f('ix_analysis_results_risk_label'), 'analysis_results', ['risk_label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_results_risk_label'), table_name='analysis_results')
    op.drop_index('ix_analysis_results_label_score', table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_content_id'), table_name='analysis_results')
    op.drop_index('ix_analysis_results_content_analyzed_at', table_name='analysis_results')
    op.drop_index(op.f('ix_analysis_results_analyzed_at'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_alerts_resolved'), table_name='alerts')
    op.drop_index('ix_alerts_created_resolved', table_name='alerts')
    op.drop_index('ix_alerts_content_resolved', table_name='alerts')
    op.drop_index(op.f('ix_alerts_content_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_content_items_source_collected_at', table_name='content_items')
    op.drop_index(op.f('ix_content_items_source'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_collected_at'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index('ix_collection_runs_status_started', table_name='collection_runs')
    op.drop_index(op.f('ix_collection_runs_status'), table_name='collection_runs')
    op.drop_index(op.f('ix_collection_runs_started_at'), table_name='collection_runs')
    op.drop_index('ix_collection_runs_source_started', table_name='collection_runs')
    op.drop_index(op.f('ix_collection_runs_source'), table_name='collection_runs')
    op.drop_table('collection_runs')
    # ### end Alembic commands ###
