"""Add User model

Revision ID: cca33144f5c0
Revises: 1dfaed3c4645
Create Date: 2026-06-11 17:57:28.998798+00:00

"""
from alembic import op
import sqlalchemy as sa
import os
import uuid
from passlib.context import CryptContext



revision = 'cca33144f5c0'
down_revision = '1dfaed3c4645'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    admin_user = os.getenv("ADMIN_USERNAME")
    admin_pass = os.getenv("ADMIN_PASSWORD")
    if admin_user and admin_pass:
        pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto", bcrypt__rounds=12)
        hashed = pwd_context.hash(admin_pass)
        op.execute(
            sa.text(
                "INSERT INTO users (id, username, hashed_password, role, is_active) "
                "VALUES (:id, :username, :hashed_password, :role, :is_active)"
            ),
            {
                "id": str(uuid.uuid4()),
                "username": admin_user,
                "hashed_password": hashed,
                "role": "ADMIN",
                "is_active": True,
            }
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
