"""alert_fixes

Revision ID: 6b6b614f7975
Revises: 9bc13418fd30
Create Date: 2026-06-09 11:55:41.719530+00:00

"""
from alembic import op
import sqlalchemy as sa



revision = '6b6b614f7975'
down_revision = '9bc13418fd30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='risk_label', native_enum=False, length=32), nullable=False, server_default='high'))
    op.add_column('alerts', sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('alerts', sa.Column('suppress_until', sa.DateTime(timezone=True), nullable=True))
    op.create_index('uq_alerts_content_unresolved', 'alerts', ['content_id'], unique=True, postgresql_where=sa.text('resolved = false'))
    op.create_index('ix_analysis_results_content_analyzed_desc', 'analysis_results', ['content_id', sa.literal_column('analyzed_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analysis_results_content_analyzed_desc', table_name='analysis_results')
    op.drop_index('uq_alerts_content_unresolved', table_name='alerts', postgresql_where=sa.text('resolved = false'))
    op.drop_column('alerts', 'suppress_until')
    op.drop_column('alerts', 'escalated_at')
    op.drop_column('alerts', 'severity')
    # ### end Alembic commands ###
