"""add source_reliability_rating

Revision ID: bc2bfbb21f34
Revises: 112038031a58
Create Date: 2026-06-11 14:12:10.655601+00:00

"""
from alembic import op
import sqlalchemy as sa



revision = 'bc2bfbb21f34'
down_revision = '112038031a58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_reports', sa.Column('source_reliability_rating', sa.String(length=10), nullable=False, server_default='C / 2'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence_reports', 'source_reliability_rating')
    # ### end Alembic commands ###
