"""add report links

Revision ID: 1dfaed3c4645
Revises: bc2bfbb21f34
Create Date: 2026-06-11 14:23:15.496799+00:00

"""
from alembic import op
import sqlalchemy as sa



revision = '1dfaed3c4645'
down_revision = 'bc2bfbb21f34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM evidence_reports")
    op.add_column('evidence_reports', sa.Column('content_id', sa.UUID(), nullable=False))
    op.add_column('evidence_reports', sa.Column('alert_id', sa.UUID(), nullable=True))
    op.add_column('evidence_reports', sa.Column('report_ref', sa.String(length=64), nullable=False))
    op.add_column('evidence_reports', sa.Column('generated_by', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_evidence_reports_alert_id'), 'evidence_reports', ['alert_id'], unique=False)
    op.create_index(op.f('ix_evidence_reports_content_id'), 'evidence_reports', ['content_id'], unique=False)
    op.create_foreign_key(None, 'evidence_reports', 'alerts', ['alert_id'], ['id'])
    op.create_foreign_key(None, 'evidence_reports', 'content_items', ['content_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evidence_reports', type_='foreignkey')
    op.drop_constraint(None, 'evidence_reports', type_='foreignkey')
    op.drop_index(op.f('ix_evidence_reports_content_id'), table_name='evidence_reports')
    op.drop_index(op.f('ix_evidence_reports_alert_id'), table_name='evidence_reports')
    op.drop_column('evidence_reports', 'generated_by')
    op.drop_column('evidence_reports', 'report_ref')
    op.drop_column('evidence_reports', 'alert_id')
    op.drop_column('evidence_reports', 'content_id')
    # ### end Alembic commands ###
