"""audit_logging_improvements

Revision ID: 72f90687bc00
Revises: 1ac44c8907ef
Create Date: 2026-06-12 12:21:03.750741+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '72f90687bc00'
down_revision = '1ac44c8907ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add analyst_id column
    op.add_column('audit_logs', sa.Column('analyst_id', sa.Uuid(), nullable=True))
    
    # 2. Backfill analyst_id from users table
    op.execute("""
        UPDATE audit_logs
        SET analyst_id = users.id
        FROM users
        WHERE audit_logs.analyst = users.username;
    """)
    
    # 3. Convert free-text details to JSON string
    op.execute("""
        UPDATE audit_logs 
        SET details = jsonb_build_object('message', details)::text 
        WHERE details IS NOT NULL AND details NOT LIKE '{%';
    """)
    
    # 4. Alter details column to JSONB
    op.alter_column('audit_logs', 'details',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='details::jsonb')
               
    op.create_index('ix_audit_logs_action_timestamp', 'audit_logs', ['action', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_analyst_id'), 'audit_logs', ['analyst_id'], unique=False)
    op.create_index('ix_audit_logs_analyst_timestamp', 'audit_logs', ['analyst', 'timestamp'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['analyst_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    
    # 5. Revoke UPDATE and DELETE on audit_logs
    op.execute("""
        DO $$
        BEGIN
            EXECUTE 'REVOKE UPDATE, DELETE ON audit_logs FROM ' || current_user;
        END $$;
    """)
    op.execute("REVOKE UPDATE, DELETE ON audit_logs FROM PUBLIC;")
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index('ix_audit_logs_analyst_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_analyst_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_timestamp', table_name='audit_logs')
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('audit_logs', 'analyst_id')
    # ### end Alembic commands ###
