"""apply db review fixes

Revision ID: 5537be644d83
Revises: a1b2c3d4e5f6
Create Date: 2026-06-07 17:11:17.122508+00:00

"""
from alembic import op
import sqlalchemy as sa



revision = '5537be644d83'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_content_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_resolved'), table_name='alerts')
    op.create_index('ix_alerts_notified_via_gin', 'alerts', ['notified_via'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_analysis_results_content_id'), table_name='analysis_results')
    op.create_index('ix_analysis_results_nlp_flags_gin', 'analysis_results', ['nlp_flags'], unique=False, postgresql_using='gin')
    op.create_index('ix_analysis_results_score_breakdown_gin', 'analysis_results', ['score_breakdown'], unique=False, postgresql_using='gin')
    op.create_index('ix_analysis_results_vision_flags_gin', 'analysis_results', ['vision_flags'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_collection_runs_source'), table_name='collection_runs')
    op.drop_index(op.f('ix_collection_runs_status'), table_name='collection_runs')
    op.create_index('ix_collection_runs_errors_gin', 'collection_runs', ['errors'], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_content_items_source'), table_name='content_items')
    op.create_index('ix_content_items_active', 'content_items', ['collected_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_content_items_media_urls_gin', 'content_items', ['media_urls'], unique=False, postgresql_using='gin')
    op.create_index('ix_content_items_metadata_gin', 'content_items', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('ix_evidence_reports_evidence_data_gin', 'evidence_reports', ['evidence_data'], unique=False, postgresql_using='gin')
    op.create_index('ix_posts_metadata_gin', 'posts', ['metadata'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_metadata_gin', table_name='posts', postgresql_using='gin')
    op.drop_index('ix_evidence_reports_evidence_data_gin', table_name='evidence_reports', postgresql_using='gin')
    op.drop_index('ix_content_items_metadata_gin', table_name='content_items', postgresql_using='gin')
    op.drop_index('ix_content_items_media_urls_gin', table_name='content_items', postgresql_using='gin')
    op.drop_index('ix_content_items_active', table_name='content_items', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_content_items_source'), 'content_items', ['source'], unique=False)
    op.drop_index('ix_collection_runs_errors_gin', table_name='collection_runs', postgresql_using='gin')
    op.create_index(op.f('ix_collection_runs_status'), 'collection_runs', ['status'], unique=False)
    op.create_index(op.f('ix_collection_runs_source'), 'collection_runs', ['source'], unique=False)
    op.drop_index('ix_analysis_results_vision_flags_gin', table_name='analysis_results', postgresql_using='gin')
    op.drop_index('ix_analysis_results_score_breakdown_gin', table_name='analysis_results', postgresql_using='gin')
    op.drop_index('ix_analysis_results_nlp_flags_gin', table_name='analysis_results', postgresql_using='gin')
    op.create_index(op.f('ix_analysis_results_content_id'), 'analysis_results', ['content_id'], unique=False)
    op.drop_index('ix_alerts_notified_via_gin', table_name='alerts', postgresql_using='gin')
    op.create_index(op.f('ix_alerts_resolved'), 'alerts', ['resolved'], unique=False)
    op.create_index(op.f('ix_alerts_content_id'), 'alerts', ['content_id'], unique=False)
    # ### end Alembic commands ###
