"""Add engine_version and weights_snapshot

Revision ID: 89bc8e3ff9d7
Revises: f8a2b1c9d3e7
Create Date: 2026-06-09 10:09:48.462592+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '89bc8e3ff9d7'
down_revision = 'f8a2b1c9d3e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('engine_version', sa.String(length=128), nullable=True))
    op.add_column('analysis_results', sa.Column('weights_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'weights_snapshot')
    op.drop_column('analysis_results', 'engine_version')
    # ### end Alembic commands ###
